### PR TITLE
Try to fix pusher (stackoverflow 43196598)

### PR DESCRIPTION
**Pull request by bergonzzi**

### CODE REVIEW

**Comment by bergonzzi** [comment]
ok

**Comment by fredsted** [comment]
Hi, what's the issue? :)

**Comment by bergonzzi** [comment]
Hi, sorry about this, I thought I was doing it on my fork but then I realised I was on the wrong URL ;)

In any case, I do have an issue running this on my own EC2 instance. I can run it fairly easily using the image provided here https://hub.docker.com/r/dahyphenn/webhook.site/ but this one seems to be outdated, the latest build is from 1 year ago. So I tried building the image myself and then running it with docker or docker-compose but I get 2 errors on the Chrome console:

    bundle.js:5527 Uncaught ReferenceError: Pusher is not defined
    at PusherConnector.connect (bundle.js:5527)
    at PusherConnector.Connector (bundle.js:5175)
    at new PusherConnector (bundle.js:5518)
    at new Echo (bundle.js:5692)
    at Object.57.laravel-echo (bundle.js:9185)
    at s (bundle.js:1)
    at e (bundle.js:1)
    at bundle.js:1

and

    Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.4.5/$injector/modulerr?p0=app&p1=Error%3A%20%5B%24injector%3Anomod%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.4.5%2F%24injector%2Fnomod%3Fp0%3Dapp%0A%20%20%20%20at%20http%3A%2F%2Fmyhost%2Fassets%2Fscripts%2Flibs%2Fangular.min.js%3A6%3A416%0A%20%20%20%20at%20http%3A%2F%2Fmyhost%2Fassets%2Fscripts%2Flibs%2Fangular.min.js%3A24%3A78%0A%20%20%20%20at%20a%20(http%3A%2F%2Fmyhost%2Fassets%2Fscripts%2Flibs%2Fangular.min.js%3A23%3A141)%0A%20%20%20%20at%20http%3A%2F%2Fmyhost%2Fassets%2Fscripts%2Flibs%2Fangular.min.js%3A23%3A384%0A%20%20%20%20at%20http%3A%2F%2Fmyhost%2Fassets%2Fscripts%2Flibs%2Fangular.min.js%3A37%3A332%0A%20%20%20%20at%20n%20(http%3A%2F%2Fmyhost%2Fassets%2Fscripts%2Flibs%2Fangular.min.js%3A7%3A322)%0A%20%20%20%20at%20g%20(http%3A%2F%2Fmyhost%2Fassets%2Fscripts%2Flibs%2Fangular.min.js%3A37%3A180)%0A%20%20%20%20at%20eb%20(http%3A%2F%2Fmyhost%2Fassets%2Fscripts%2Flibs%2Fangular.min.js%3A40%3A435)%0A%20%20%20%20at%20d%20(http%3A%2F%2Fmyhost%2Fassets%2Fscripts%2Flibs%2Fangular.min.js%3A19%3A381)%0A%20%20%20%20at%20yc%20(http%3A%2F%2Fmyhost%2Fassets%2Fscripts%2Flibs%2Fangular.min.js%3A20%3A179)
        at angular.min.js:6
        at angular.min.js:38
        at n (angular.min.js:7)
        at g (angular.min.js:37)
        at eb (angular.min.js:40)
        at d (angular.min.js:19)
        at yc (angular.min.js:20)
        at Zd (angular.min.js:19)
        at HTMLDocument.<anonymous> (angular.min.js:292)
        at i (jquery-2.2.2.min.js:2)    Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.4.5/$injector/modulerr?p0=app&p1=Error%3A%20%5B%24injector%3Anomod%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.4.5%2F%24injector%2Fnomod%3Fp0%3Dapp%0A%20%20%20%20at%20http%3A%2F%2Fmyhost%2Fassets%2Fscripts%2Flibs%2Fangular.min.js%3A6%3A416%0A%20%20%20%20at%20http%3A%2F%2Fmyhost%2Fassets%2Fscripts%2Flibs%2Fangular.min.js%3A24%3A78%0A%20%20%20%20at%20a%20(http%3A%2F%2Fmyhost%2Fassets%2Fscripts%2Flibs%2Fangular.min.js%3A23%3A141)%0A%20%20%20%20at%20http%3A%2F%2Fmyhost%2Fassets%2Fscripts%2Flibs%2Fangular.min.js%3A23%3A384%0A%20%20%20%20at%20http%3A%2F%2Fmyhost%2Fassets%2Fscripts%2Flibs%2Fangular.min.js%3A37%3A332%0A%20%20%20%20at%20n%20(http%3A%2F%2Fmyhost%2Fassets%2Fscripts%2Flibs%2Fangular.min.js%3A7%3A322)%0A%20%20%20%20at%20g%20(http%3A%2F%2Fmyhost%2Fassets%2Fscripts%2Flibs%2Fangular.min.js%3A37%3A180)%0A%20%20%20%20at%20eb%20(http%3A%2F%2Fmyhost%2Fassets%2Fscripts%2Flibs%2Fangular.min.js%3A40%3A435)%0A%20%20%20%20at%20d%20(http%3A%2F%2Fmyhost%2Fassets%2Fscripts%2Flibs%2Fangular.min.js%3A19%3A381)%0A%20%20%20%20at%20yc%20(http%3A%2F%2Fmyhost%2Fassets%2Fscripts%2Flibs%2Fangular.min.js%3A20%3A179)
        at angular.min.js:6
        at angular.min.js:38
        at n (angular.min.js:7)
        at g (angular.min.js:37)
        at eb (angular.min.js:40)
        at d (angular.min.js:19)
        at yc (angular.min.js:20)
        at Zd (angular.min.js:19)
        at HTMLDocument.<anonymous> (angular.min.js:292)
        at i (jquery-2.2.2.min.js:2)

(changed my actual ec2 url to myhost above)

I followed the instructions here in your repo and docker hub and configured pusher in the .env file. As for the other error, I searched a bit and found some possible issues with angular but I really don't know much about it. Maybe you can shed some light?

**Comment by fredsted** [comment]
Hmm, I haven't tried running it with Docker yet. You might need to run `nom install` & `gulp` to compile the frontend. Also make sure all the js files from /public are included.

**Pull request closed without merging**
