### PR TITLE
Sorting requests by the most recent first

### PR DESCRIPTION
**Pull request by mnfjorge**
I'm using this tool, but after many tests, I have to click "Load more" a lot of times to see the most recents.

### CODE REVIEW

**Comment by fredsted** [comment]
Hi @mnfjorge, thanks for this, great idea. Seems obvious to do this. I don't know why I didn't think about this before! 😃  I think some more work is needed though, I'd like requests showing up on top on receiving a push as well.

**Comment by mnfjorge** [comment]
Awesome ;)
Will do it as soon as I have some free time!

**Comment by reindert-vetter** [comment]
It would be nice if this would be merged!

**Comment by fredsted** [comment]
Closing this since this has been fixed for a while now, and doesn't apply anymore since Webhook.site is using Redis now :)

**Pull request closed without merging**
